name: Run Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Run Tests API
        run: ./gradlew testApi

      - name: Run Tests Web UI
        run: ./gradlew testWeb

      - name: Archive API test results
        uses: actions/upload-artifact@v4.3.0
        if: always() #always() # success() , failure(), canceled()
        with:
          name: API Test reports
          path: build/reports/tests/testApi  # Path to test reports

      - name: Archive Web test results
        uses: actions/upload-artifact@v4.3.0
        if: always() #always() # success() , failure(), canceled()
        with:
          name: Web Test reports
          path: target/web-report.html  # Path to test reports
